//! Rendering — turn a [`ZaindariReport`] into a self-contained HTML report a
//! non-engineer can read, plus a terse terminal summary.
//!
//! The HTML is one file: inline CSS, no JS, no CDN, no external assets. Plain
//! and credible — a traffic light per pillar, a one-sentence headline, metric
//! tables with baseline deltas, and findings grouped by severity.

use crate::report::{
    Finding, Metric, MetricDirection, PillarResult, PillarStatus, Severity, ZaindariReport,
};
use std::fmt::Write as _;

/// Render the full self-contained HTML report.
pub fn to_html(report: &ZaindariReport) -> String {
    let mut s = String::with_capacity(8 * 1024);
    s.push_str("<!DOCTYPE html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">");
    s.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
    s.push_str("<title>zaindari report</title>\n<style>\n");
    s.push_str(CSS);
    s.push_str("</style></head><body>\n");
    s.push_str("<header><h1>zaindari report</h1>");
    let _ = write!(
        s,
        "<p class=\"sub\">LLM-trust check across Gate, Guard and Watch. Schema v{}.</p>",
        report.schema_version
    );
    s.push_str("</header>\n<main>\n");

    render_pillar_card(
        &mut s,
        "Gate",
        "Pre-ship eval quality",
        report.pillars.gate.as_ref(),
    );
    render_pillar_card(
        &mut s,
        "Guard",
        "Runtime rule enforcement",
        report.pillars.guard.as_ref(),
    );
    render_pillar_card(
        &mut s,
        "Watch",
        "Production drift detection",
        report.pillars.watch.as_ref(),
    );

    s.push_str("</main>\n<footer><p>Generated by zaindari — orchestrator over aatxe, iratxo, cardinal-map.</p></footer>\n");
    s.push_str("</body></html>\n");
    s
}

fn render_pillar_card(s: &mut String, name: &str, blurb: &str, pillar: Option<&PillarResult>) {
    let (status, headline) = match pillar {
        Some(p) => (p.status, p.headline.as_str()),
        None => (PillarStatus::Skipped, "Not configured."),
    };
    let cls = status_class(status);
    let _ = write!(
        s,
        "<section class=\"card {cls}\">\n<div class=\"card-head\">"
    );
    let _ = write!(
        s,
        "<span class=\"dot {cls}\"></span><h2>{}</h2><span class=\"badge {cls}\">{}</span>",
        esc(name),
        status.label()
    );
    let _ = write!(s, "</div>\n<p class=\"blurb\">{}</p>", esc(blurb));
    let _ = writeln!(s, "<p class=\"headline\">{}</p>", esc(headline));

    if let Some(p) = pillar {
        if !p.metrics.is_empty() {
            render_metric_table(s, &p.metrics);
        }
        if !p.findings.is_empty() {
            render_findings(s, &p.findings);
        }
        if let Some(raw) = &p.raw_ref {
            let _ = write!(
                s,
                "<p class=\"raw\">raw engine output: <code>{}</code></p>",
                esc(raw)
            );
        }
    }
    s.push_str("</section>\n");
}

fn render_metric_table(s: &mut String, metrics: &[Metric]) {
    s.push_str("<table class=\"metrics\"><thead><tr><th>metric</th><th>value</th><th>baseline</th><th>change</th></tr></thead><tbody>\n");
    for m in metrics {
        let _ = write!(
            s,
            "<tr><td>{}</td><td>{}</td>",
            esc(&m.name),
            fmt_num(m.value)
        );
        match m.baseline {
            Some(b) => {
                let _ = write!(s, "<td>{}</td>", fmt_num(b));
            }
            None => s.push_str("<td class=\"muted\">—</td>"),
        }
        match m.delta {
            Some(d) => {
                let cls = delta_class(m);
                let _ = write!(s, "<td class=\"{cls}\">{}</td>", fmt_delta(d));
            }
            None => s.push_str("<td class=\"muted\">—</td>"),
        }
        s.push_str("</tr>\n");
    }
    s.push_str("</tbody></table>\n");
}

fn render_findings(s: &mut String, findings: &[Finding]) {
    s.push_str("<div class=\"findings\">\n");
    for sev in Severity::all_worst_first() {
        let group: Vec<&Finding> = findings.iter().filter(|f| f.severity == sev).collect();
        if group.is_empty() {
            continue;
        }
        let cls = severity_class(sev);
        let _ = write!(
            s,
            "<h3 class=\"sev {cls}\">{} ({})</h3>\n<ul>",
            sev.label(),
            group.len()
        );
        for f in group {
            let _ = write!(s, "<li><strong>{}</strong>", esc(&f.title));
            if let Some(loc) = &f.location {
                let _ = write!(s, " <code>{}</code>", esc(loc));
            }
            let _ = writeln!(
                s,
                "<br><span class=\"detail\">{}</span></li>",
                esc(&f.detail)
            );
        }
        s.push_str("</ul>\n");
    }
    s.push_str("</div>\n");
}

fn status_class(s: PillarStatus) -> &'static str {
    match s {
        PillarStatus::Pass => "pass",
        PillarStatus::Fail => "fail",
        PillarStatus::Warn => "warn",
        PillarStatus::Skipped => "skipped",
        PillarStatus::EngineMissing => "missing",
    }
}

fn severity_class(s: Severity) -> &'static str {
    match s {
        Severity::Critical => "fail",
        Severity::Major => "warn",
        Severity::Minor | Severity::Nit | Severity::Info => "skipped",
    }
}

fn delta_class(m: &Metric) -> &'static str {
    if m.regressed() {
        return "fail";
    }
    match (m.delta, m.direction) {
        (Some(d), MetricDirection::HigherBetter) if d > 0.0 => "pass",
        (Some(d), MetricDirection::LowerBetter) if d < 0.0 => "pass",
        _ => "muted",
    }
}

fn fmt_num(v: f64) -> String {
    if v.fract() == 0.0 && v.abs() < 1e15 {
        format!("{}", v as i64)
    } else {
        format!("{v:.3}")
    }
}

fn fmt_delta(d: f64) -> String {
    let n = if d.fract() == 0.0 && d.abs() < 1e15 {
        format!("{}", d as i64)
    } else {
        format!("{d:.3}")
    };
    if d > 0.0 {
        format!("+{n}")
    } else {
        n
    }
}

/// Minimal HTML escape for text nodes / attribute values.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

/// A terse multi-line terminal summary (one block per pillar).
pub fn to_text(report: &ZaindariReport) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "zaindari report (schema v{})", report.schema_version);
    render_text_pillar(&mut s, "gate", report.pillars.gate.as_ref());
    render_text_pillar(&mut s, "guard", report.pillars.guard.as_ref());
    render_text_pillar(&mut s, "watch", report.pillars.watch.as_ref());
    s
}

fn render_text_pillar(s: &mut String, name: &str, pillar: Option<&PillarResult>) {
    match pillar {
        None => {
            let _ = writeln!(s, "  {name:<6} ·  -  not configured");
        }
        Some(p) => {
            let _ = writeln!(s, "  {name:<6} · {:<14} {}", p.status.label(), p.headline);
            for f in &p.findings {
                let loc = f
                    .location
                    .as_deref()
                    .map(|l| format!(" [{l}]"))
                    .unwrap_or_default();
                let _ = writeln!(s, "           - {}: {}{}", f.severity.label(), f.title, loc);
            }
        }
    }
}

const CSS: &str = r#"
:root{--ok:#1a7f37;--bad:#cf222e;--warn:#9a6700;--skip:#57606a;--bg:#fff;--fg:#1f2328;--line:#d0d7de}
*{box-sizing:border-box}
body{margin:0;font:16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;color:var(--fg);background:#f6f8fa}
header{padding:28px 24px 8px;max-width:880px;margin:0 auto}
h1{margin:0;font-size:24px}
.sub{color:var(--skip);margin:4px 0 0}
main{max-width:880px;margin:0 auto;padding:12px 24px 40px}
.card{background:var(--bg);border:1px solid var(--line);border-left-width:5px;border-radius:8px;padding:18px 20px;margin:16px 0}
.card.pass{border-left-color:var(--ok)}
.card.fail{border-left-color:var(--bad)}
.card.warn{border-left-color:var(--warn)}
.card.skipped,.card.missing{border-left-color:var(--skip)}
.card-head{display:flex;align-items:center;gap:10px}
.card-head h2{margin:0;font-size:19px;flex:0 0 auto}
.dot{width:12px;height:12px;border-radius:50%;flex:0 0 auto}
.dot.pass{background:var(--ok)}.dot.fail{background:var(--bad)}.dot.warn{background:var(--warn)}
.dot.skipped,.dot.missing{background:var(--skip)}
.badge{margin-left:auto;font-size:12px;font-weight:600;letter-spacing:.04em;padding:2px 8px;border-radius:999px;color:#fff}
.badge.pass{background:var(--ok)}.badge.fail{background:var(--bad)}.badge.warn{background:var(--warn)}
.badge.skipped,.badge.missing{background:var(--skip)}
.blurb{color:var(--skip);margin:8px 0 2px;font-size:13px}
.headline{margin:6px 0 14px;font-size:16px}
table.metrics{width:100%;border-collapse:collapse;font-size:14px;margin:6px 0 8px}
table.metrics th,table.metrics td{text-align:left;padding:6px 10px;border-bottom:1px solid var(--line)}
table.metrics th{color:var(--skip);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.03em}
table.metrics td.pass{color:var(--ok);font-weight:600}
table.metrics td.fail{color:var(--bad);font-weight:600}
table.metrics td.muted{color:var(--skip)}
.findings h3.sev{font-size:13px;text-transform:uppercase;letter-spacing:.04em;margin:14px 0 4px}
.sev.fail{color:var(--bad)}.sev.warn{color:var(--warn)}.sev.skipped{color:var(--skip)}
.findings ul{margin:0 0 8px;padding-left:18px}
.findings li{margin:4px 0}
.detail{color:var(--skip);font-size:14px}
code{background:#eff1f3;padding:1px 5px;border-radius:4px;font-size:13px}
.raw{font-size:12px;color:var(--skip);margin-top:10px}
footer{max-width:880px;margin:0 auto;padding:0 24px 40px;color:var(--skip);font-size:13px}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::report::{Finding, Metric, MetricDirection, PillarResult, PillarStatus, Severity};

    fn sample_report() -> ZaindariReport {
        let mut r = ZaindariReport::empty();
        let mut gate = PillarResult::new(PillarStatus::Pass, "Eval gate held: critical F1 0.90.");
        gate.metrics.push(Metric::with_baseline(
            "council.critical_f1",
            0.90,
            0.857,
            MetricDirection::HigherBetter,
        ));
        r.pillars.gate = Some(gate);

        let mut guard = PillarResult::new(PillarStatus::Fail, "2 guard rule case(s) failed.");
        guard.findings.push(
            Finding::new(
                Severity::Major,
                "rule case failed: promo-x",
                "triggers: expected disclaimer",
            )
            .with_location("promo-x"),
        );
        r.pillars.guard = Some(guard);

        let mut watch = PillarResult::new(PillarStatus::Warn, "1 of 3 items look anomalous.");
        watch.findings.push(Finding::new(
            Severity::Major,
            "anomalous skill: Klingon",
            "cardinality 0.94 — no peers nearby",
        ));
        r.pillars.watch = Some(watch);
        r
    }

    #[test]
    fn html_is_self_contained_with_no_external_refs() {
        let html = to_html(&sample_report());
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<style>"));
        // No external assets / scripts.
        assert!(!html.contains("<script"));
        assert!(!html.contains("http://"));
        assert!(!html.contains("https://"));
        assert!(!html.contains("cdn"));
    }

    #[test]
    fn html_renders_traffic_lights_and_headlines() {
        let html = to_html(&sample_report());
        assert!(html.contains(">Gate</h2>"));
        assert!(html.contains(">Guard</h2>"));
        assert!(html.contains(">Watch</h2>"));
        assert!(html.contains("PASS"));
        assert!(html.contains("FAIL"));
        assert!(html.contains("WARN"));
        assert!(html.contains("Eval gate held"));
    }

    #[test]
    fn html_shows_baseline_delta_and_findings() {
        let html = to_html(&sample_report());
        assert!(html.contains("council.critical_f1"));
        // delta +0.043 rendered.
        assert!(html.contains("+0.043"));
        assert!(html.contains("promo-x"));
        assert!(html.contains("Klingon"));
    }

    #[test]
    fn html_escapes_text() {
        let mut r = ZaindariReport::empty();
        r.pillars.gate = Some(PillarResult::new(PillarStatus::Pass, "a <b> & \"c\""));
        let html = to_html(&r);
        assert!(html.contains("a &lt;b&gt; &amp; &quot;c&quot;"));
    }

    #[test]
    fn text_summary_lists_each_pillar() {
        let txt = to_text(&sample_report());
        assert!(txt.contains("gate"));
        assert!(txt.contains("guard"));
        assert!(txt.contains("watch"));
        assert!(txt.contains("FAIL"));
    }
}
